language: cpp
compiler: g++
cache:
  apt: true
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - automake
    - autoconf
    - gcc-4.8
    - g++-4.8
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
before_script:
script: ./bootstrap && ./configure && make && make check && ./test/test
after_failure:
- autoconf --version
- autoreconf --version
- automake --version
- gcc --version
- g++ --version
- cat ./configure
